version: '3.3'
services:
    openvpn-client:
        image: dperson/openvpn-client
        container_name: openvpn-client
        network_mode: bridge
        privileged: true
        environment:
            - TZ=Europe/Moscow
            - Firewall=true
            - DNS=192.168.104.1
        ports:
            - '9117:9117/tcp'
        volumes:
            - '/home/khabarovru/1/config/openvpn-client:/vpn:rw,slave'
        devices:
            - /dev/net/tun
        restart: unless-stopped

    jackett:
        image: 'linuxserver/jackett:development'
        container_name: jackett
        network_mode: 'container:openvpn-client'
        environment:
            - TZ=Europe/Moscow
            - PUID=1000
            - PGID=100
        volumes:
            - '/home/khabarovru/1/torrents:/downloads:rw,slave'
            - '/home/khabarovru/1/config/jackett:/config:rw,slave'
        restart: unless-stopped

    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Moscow
        volumes:
        - '/home/khabarovru/1/config/sonarr:/config'
        - '/home/khabarovru/1/media/tv:/tv'
        - '/home/khabarovru/1/torrents/tv:/downloads'
        ports:
        - 8989:8989
        restart: unless-stopped

    radarr:
        image: lscr.io/linuxserver/radarr:latest
        container_name: radarr
        environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Moscow
        volumes:
        - '/home/khabarovru/1/config/radarr:/config'
        - '/home/khabarovru/1/media/movies:/movies'
        - '/home/khabarovru/1/torrents/movies:/downloads'
        ports:
        - 7878:7878
        restart: unless-stopped

    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Moscow
        - WEBUI_PORT=8080
        volumes:
        - '/home/khabarovru/1/config/qbittorrent:/config'
        - '/home/khabarovru/1/torrents:/downloads'
        ports:
        - 8080:8080
        - 6881:6881
        - 6881:6881/udp
        restart: unless-stopped

    plex:
        image: lscr.io/linuxserver/plex:latest
        container_name: plex
        network_mode: host
        environment:
        - PUID=1000
        - PGID=1000
        - VERSION=docker
        - PLEX_CLAIM= #optional
        - TZ=Europe/Moscow
        volumes:
        - '/home/khabarovru/1/config/plex:/config'
        - '/home/khabarovru/1/media/tv:/tv'
        - '/home/khabarovru/1/media/movies:/movies'
        restart: unless-stopped
